---
name: Py Lint

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Run ruff format
        run: uv run ruff format --check --force-exclude -- src

      - name: Run ruff lint
        run: uv run ruff check --force-exclude -- src

      - name: Run mypy typecheck
        run: uv run mypy --pretty -- src
