---
name: Shell Lint

on:
  push:
    paths:
      - "**.sh"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shell-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install shellcheck-py shfmt-py

      - name: Run shell format
        run: |
          find src -type f -name '*.sh' -print0 | xargs -0 -r shfmt -d -i 4 --

      - name: Run shell check
        run: |
          find src -type f -name '*.sh' -print0 | xargs -0 -r shellcheck -x -e SC2034 --
